### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by Matt-Lepley** [ieric01/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by ieric01** [comment]
Hey Matt:

Thanks for the feedback. I went to bootstrap's website and I added this line of code,
<meta name="viewport" content="width=device-width, initial-scale=1">. I hope this is what you were talking about. This meta tag is suppose to ensure proper rendering and touch zooming for mobile devices.

**Comment by Matt-Lepley** [comment]
Perfect! That is exactly what I was looking for.
Now that you have fixed this ticket feel free to close it!

**Comment by ieric01** [comment]
Thanks!!!
